apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: vm-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  namespace: {{ .namespace }}
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: quay.io/centos/centos:stream9
        command:
          - /bin/bash
          - -c
          {{ if .remove }}
          - "echo removing"
          {{ else }}
          - "echo start && sleep 60 && echo {{ .ipAddr }} echo down"
          {{ end }}