apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: oidp-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: VirtualMachine is the Schema for the virtualmachines API
      displayName: Virtual Machine
      kind: VirtualMachine
      name: virtualmachines.platform.example.com
      version: v1alpha1
  description: oidp-operator
  displayName: oidp-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - infra
  links:
  - name: Oidp Operator
    url: https://oidp-operator.domain
  maturity: alpha
  provider:
    name: oidp-operator
  version: 0.0.0
